// GENERATED by scripts/build-catalog-slots.mjs — do not edit.
// Source of truth: vendor/spec/v1_0/catalogs/basic/catalog.json (A2UI v1.0, Apache-2.0)

import type { ChildSlot } from './types.js'

/** Every component type the v1.0 basic catalog defines. */
export const BASIC_CATALOG_COMPONENTS: readonly string[] = [
    'AudioPlayer',
    'Button',
    'Card',
    'CheckBox',
    'ChoicePicker',
    'Column',
    'DateTimeInput',
    'Divider',
    'Icon',
    'Image',
    'List',
    'Modal',
    'Row',
    'Slider',
    'Tabs',
    'Text',
    'TextField',
    'Video',
]

/** Functions the basic catalog declares. Used to check our registry against the spec. */
export const BASIC_CATALOG_FUNCTIONS: readonly string[] = [
    'and',
    'email',
    'formatCurrency',
    'formatDate',
    'formatNumber',
    'formatString',
    'length',
    'not',
    'numeric',
    'openUrl',
    'or',
    'pluralize',
    'regex',
    'required',
]

/**
 * Properties that hold child references, per component type.
 * `children` / `child` become positional children; anything else becomes a named
 * prop carrying the built component(s).
 */
export const BASIC_CATALOG_SLOTS: Record<string, ChildSlot[]> = {
    Button: [
        {
            prop: 'child',
            kind: 'single',
        },
    ],
    Card: [
        {
            prop: 'child',
            kind: 'single',
        },
    ],
    Column: [
        {
            prop: 'children',
            kind: 'list',
        },
    ],
    List: [
        {
            prop: 'children',
            kind: 'list',
        },
    ],
    Modal: [
        {
            prop: 'trigger',
            kind: 'single',
        },
        {
            prop: 'content',
            kind: 'single',
        },
    ],
    Row: [
        {
            prop: 'children',
            kind: 'list',
        },
    ],
    Tabs: [
        {
            prop: 'tabs',
            kind: 'objectList',
            childKey: 'child',
        },
    ],
}
