/**
 * Bundles the on-disk BindJS catalog sources into a TypeScript module.
 *
 * The components live as real `.js` files so they stay editable, lintable and
 * pushable to Metabind — but the published package has to register them in Node, the
 * browser and the native runtimes, none of which can read this directory. So the
 * sources are inlined as strings at build time.
 *
 * Authors write `export default defineComponent(...)`; the BindJS runtime evaluates a
 * component as a CommonJS-ish module and reads `exports.default`, so that one token is
 * rewritten here — the same transform the Composer and the playground apply.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const sourceDir = join(here, '..', 'src', 'catalog', 'basic')
const outputPath = join(sourceDir, 'sources.generated.ts')

function toRuntimeSource(source) {
    return source.replace(/export\s+default\s+/g, 'exports.default = ')
}

const files = readdirSync(sourceDir)
    .filter((name) => name.endsWith('.js'))
    .sort()

const entries = files.map((file) => {
    const name = file.replace(/\.js$/, '')
    const source = toRuntimeSource(readFileSync(join(sourceDir, file), 'utf8'))

    return `    ${JSON.stringify(name)}: ${JSON.stringify(source)},`
})

const output = `// GENERATED by scripts/build-catalog.mjs — do not edit.
// Source of truth: src/catalog/basic/*.js

/** Registered component name → BindJS source, ready for \`runtime.registerComponent\`. */
export const BASIC_CATALOG_SOURCES: Record<string, string> = {
${entries.join('\n')}
}
`

writeFileSync(outputPath, output)
console.log(`build-catalog: bundled ${files.length} components → ${outputPath}`)
